#ifndef GUARD_MIX_MEGA_H
#define GUARD_MIX_MEGA_H

#include "global.h"

// This is a list of all mega evolutions usable in Mix and Mega.
// If you add a new mega stone, make sure you add it to this list, placing it before the final element.
// (i.e. add it between STONE_DRAGON_ASCENT and STONES_COUNT)
// You will also need to edit src/mix_mega.c and src/data/mix_mega.h.
enum
{
	STONE_ABOMASITE,
	STONE_ABSOLITE,
	STONE_AERODACTYLITE,
	STONE_AGGRONITE,
	STONE_ALAKAZITE,
	STONE_ALTARIANITE,
	STONE_AMPHAROSITE,
	STONE_AUDINITE,
	STONE_BANETTITE,
	STONE_BEEDRILLITE,
	STONE_BLASTOISINITE,
	STONE_BLAZIKENITE,
	STONE_CAMERUPTITE,
	STONE_CHARIZARDITE_X,
	STONE_CHARIZARDITE_Y,
	STONE_DIANCITE,
	STONE_GALLADITE,
	STONE_GARCHOMPITE,
	STONE_GARDEVOIRITE,
	STONE_GENGARITE,
	STONE_GLALITITE,
	STONE_GYARADOSITE,
	STONE_HERACRONITE,
	STONE_HOUNDOOMINITE,
	STONE_KANGASKHANITE,
	STONE_LATIASITE,
	STONE_LATIOSITE,
	STONE_LOPUNNITE,
	STONE_LUCARIONITE,
	STONE_MANECTITE,
	STONE_MAWILITE,
	STONE_MEDICHAMITE,
	STONE_METAGROSSITE,
	STONE_MEWTWONITE_X,
	STONE_MEWTWONITE_Y,
	STONE_PIDGEOTITE,
	STONE_PINSIRITE,
	STONE_SABLENITE,
	STONE_SALAMENCITE,
	STONE_SCEPTILITE,
	STONE_SCIZORITE,
	STONE_SHARPEDONITE,
	STONE_SLOWBRONITE,
	STONE_STEELIXITE,
	STONE_SWAMPERTITE,
	STONE_TYRANITARITE,
	STONE_VENUSAURITE,
	STONE_DRAGON_ASCENT,
	STONE_BLUE_ORB,
	STONE_RED_ORB,
	STONES_COUNT
};

struct MixMegaStats
{
	s8 baseAttack;
	s8 baseDefense;
	s8 baseSpAttack;
	s8 baseSpDefense;
	s8 baseSpeed;
	u8 type;
	u16 ability;
};

extern const struct MixMegaStats mixMegaStones[];

u8 ItemIdToMegaStoneId(u16 item);

#endif // GUARD_MIX_MEGA_H